// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_gen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cassette struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Song struct {
	ID         pgtype.UUID
	CassetteID pgtype.UUID
	UserID     pgtype.UUID
	SongNumber int32
	SongTime   pgtype.Int4
	Name       string
	Url        string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	IconUrl   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
